# Generated by Django 2.1 on 2018-08-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180808_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='feed.Issue'),
        ),
    ]
