# Generated by Django 2.1 on 2018-08-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180808_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='issue',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
