# Generated by Django 2.1 on 2018-08-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
