# Generated by Django 2.1 on 2018-08-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
